# Generated by Django 5.0.1 on 2024-01-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='customer_review',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model_year',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fueltype',
            name='fuel_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neworused',
            name='new_or_used',
            field=models.CharField(choices=[('N', 'new'), ('U', 'used')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='pricerange',
            name='price_range',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=1),
        ),
        migrations.AddField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('c', 'compact'), ('m', 'midsize'), ('f', 'full_size')], default='c', max_length=1),
        ),
        migrations.DeleteModel(
            name='CarType',
        ),
        migrations.DeleteModel(
            name='CustomerReview',
        ),
        migrations.DeleteModel(
            name='ModelYear',
        ),
    ]
