# Generated by Django 5.0.1 on 2024-01-17 12:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_car_car_type_remove_car_customer_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='inventory',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.carmodel'),
            preserve_default=False,
        ),
    ]
