# Generated by Django 5.0.1 on 2024-02-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_carmodel_alter_car_inventory_alter_car_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='car',
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('P', 'petrol'), ('D', 'diesel'), ('E', 'electric')], max_length=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='new_or_used',
            field=models.CharField(choices=[('N', 'new'), ('U', 'used')], max_length=1),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='car',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='car',
            name='size',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='birth_date',
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='FuelType',
        ),
        migrations.DeleteModel(
            name='NewOrUsed',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='PriceRange',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
