# Generated by Django 5.0.1 on 2024-02-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_buyer_car_model_buyer_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='model',
        ),
        migrations.AddField(
            model_name='brand',
            name='car_model',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Car_Model',
        ),
    ]
