# Generated by Django 5.0.1 on 2024-02-20 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_car_car_model_remove_buyer_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.brand'),
            preserve_default=False,
        ),
    ]
