# Generated by Django 5.0.1 on 2024-02-21 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_deal_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='new_or_used',
            field=models.CharField(choices=[('N', 'new'), ('U', 'used')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
