# Generated by Django 5.0.1 on 2024-02-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_buyer_brand_buyer_new_or_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='brand',
        ),
        migrations.AddField(
            model_name='buyer',
            name='brand',
            field=models.ManyToManyField(to='store.brand'),
        ),
    ]
